name: livechat_example
description: Example app for the LiveChat Flutter SDK.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.11.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  livechat_flutter:
    path: ../
dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
