import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const file = fs.readFileSync(new URL('../lib/src/bridge.dart', import.meta.url), 'utf8');
const script = file.split("r'''")[1].split("''';")[0];
const events = [];
const context = vm.createContext({window: {}, LiveChatFlutter: {postMessage: s => events.push(JSON.parse(s))}});
vm.runInContext(script, context);
assert.equal(context.window.LiveChat.q.length, 3);
vm.runInContext(script, context);
assert.equal(context.window.LiveChat.q.length, 3, 'bootstrap must not subscribe twice');
const subscriptions = new Map(context.window.LiveChat.q.map(([, [event, callback]]) => [event, callback]));
subscriptions.get('ready')();
subscriptions.get('message')({message: {id: 7, body: 'Hello', senderType: 'operator'}});
subscriptions.get('error')({message: 'Offline'});
assert.deepEqual(events, [{type:'ready'}, {type:'message',message:{id:7,body:'Hello',senderType:'operator'}}, {type:'error', description:'Offline'}]);
let value;
context.window.LiveChat.identify = data => { value = data; };
context.window.__livechatCall('identify', [{externalId:'member'}]);
assert.equal(value.externalId, 'member');
console.log('Bridge: queue, ready/message/error forwarding, idempotence, installed SDK calls passed.');
